### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Sheraf1** [Mtihc/bustabit-script-simulator#6]
Hi,

Very helpful script, thank you so much for this!

I'd like to add a few features to it, any chance you would release the unobfuscated code?

I'd like to add a checkbox that would generate a random hash every time we decide to run the script, and also add a loop feature that would for example run the script 500 times with different hash and calculate an average profit/loss

Thanks!

**Comment by Mtihc** [comment]
Hello,

Glad you like it.

I'm considering to make a "premium" version behind a paywall (after I fixed the performance issues)
So, the answer is no. I will not release the code. Sorry.
